### ISSUE TITLE
upgrade from rack-attack 6.3.1 to 6.5.0 is giving error on custom methods

### ISSUE THREAD

**Issue by anikettstiwari** [rack/rack-attack#549]
When upgrade from rack-attack 6.3.1 to 6.5.0 it is unable to fetch any custom methods

undefined method `comment' for #<Hash:0x00007fd2b4f41530>

As per the documentation I updated the method from throttled_callback to  throttled_response

```
Rack::Attack.throttled_response = lambda do |request|
  details = {restriction: {name: 'asdas', comment: request.comment}}

  
  if Feature.enabled?(:some_feature)
    restrict_user(request.token, details) if request.update_password?
  end
end


I have added a lot of method but now after upgradating unable to access any of the method inside the throttled_callback

class Rack::Attack
  class Request < ::Rack::Request
    ##
    ## Helper Functions
    ##
    # Get the real IP Address of the user/client
    attr_accessor :comment

    def remote_ip
      @remote_ip ||= get_header('HTTP_X_FORWARDED_FOR').try(:to_s)
    end

    def body_params
      unless @body_params 
        @body_params = JSON.parse(body.read)
        body.rewind
      end
      @body_params
    end

    def username
      (body_params["username"]).to_s.downcase
    end

    def login?
      self.path == '/user_sign_in'
    end
end

throttle("ip:user-key-min", limit: 10, period: 1.minute) do |req|
  if req.login?
    req.comment = "some comment"
    req.remote_ip
  end
end
```

**Comment by grzuy** [comment]
Hi @anikettstiwari ,

For `v6.x` refer to documentation in https://github.com/rack/rack-attack/blob/6-stable/README.md.

Sorry for the confusion.

**Comment by anikettstiwari** [comment]
@grzuy  I have refer the documentation and change throttled_callback to throttled_response but still no luck for me. I am getting the same error

**Comment by grzuy** [comment]
Hi @anikettstiwari,

Are you expecting an env `Hash` or a `Request` from the `lambda`?
I think that's what your exception is coming from if I interpret correctly.

Thanks.

**Comment by anikettstiwari** [comment]
Hi @grzuy, When i am inside the throttled_response

```
Rack::Attack.throttled_response = lambda do |request|
  details = {restriction: {name: 'asdas', comment: request.comment}}
  
  if Feature.enabled?(:some_feature)
    restrict_user(request.token, details) if request.update_password?
  end
end
```
So, the request object is not able to access the **comment** or any **method** inside the **class Request < ::Rack::Request** after upgrading to latest version of rack-attack.

In version 6.3.1 in the request object i was able to access method from the class Request inside the throttled_callback

request.methods
[ :comment, :username, , :comment=, :body_params, : remote_ip, login?]

**Comment by grzuy** [comment]
Hi @anikettstiwari ,

As per rack-attack v6.5.0 the `throttled_response` is called with an env `Hash` as the argument, not a `Rack::Attack::Request` object.

You would need to change it to 

```rb
Rack::Attack.throttled_response = lambda do |env|
  request = Rack::Attack::Request.new(env)

  # rest of your code accessing request.comment
end
```

**Comment by anikettstiwari** [comment]
@grzuy  Thanks for the response. So, now i am able to access the method inside the throttled_response. But the attr_accessor methods still not fetching any value

```
Rack::Attack.throttled_response = lambda do |env|
  request = Rack::Attack::Request.new(env)

  #Now when I check request.methods it is giving me result but the attr_accessor method is not giving any value

  request.methods
[ :comment, :username, , :comment=, :body_params, : remote_ip, login?]

  #When I check request.comment it is giving me nil

  # rest of your code accessing request.comment
end

class Rack::Attack
  class Request < ::Rack::Request
    ##
    ## Helper Functions
    ##
    # Get the real IP Address of the user/client
    attr_accessor :comment

    def remote_ip
      @remote_ip ||= get_header('HTTP_X_FORWARDED_FOR').try(:to_s)
    end

    def body_params
      unless @body_params 
        @body_params = JSON.parse(body.read)
        body.rewind
      end
      @body_params
    end

    def username
      (body_params["username"]).to_s.downcase
    end

    def login?
      self.path == '/user_sign_in'
    end
end

throttle("id:some-key", limit: 5, period: 1.minute) do |req|
        Rails.logger.info("user search #{req.user_id}")
        req.comment = "my comment"
        req.user_id
  end

```

**Comment by anikettstiwari** [comment]
@grzuy Shall I open a new issue?
